Refactor pre-commit

diff --git a/git_hooks/pre-commit b/git_hooks/pre-commit
--- a/git_hooks/pre-commit
+++ b/git_hooks/pre-commit
@@ -1,38 +1,27 @@
 #!/bin/sh
 
-result=$(dart format .)
-exitCode=$? # If the exitCode is zero, then command executed successfully.
+# Function to run Dart command and check exit code
+run_command() {
+  directory="$1"
+  command="$2"
 
-if [ $exitCode  -ne 0 ]; then
+  cd "$directory" || exit 1
+
+  result=$(eval "$command")
   echo "$result"
-  echo "Dart format found issues, please fix them."
-  exit 1
-fi
+}
+
+# Change directory to app/lib and run dart format
+run_command "app/lib" "dart format ." "dart format"
+
 echo "Finished running dart format command."
 
-################################################################
+# Run dart analyze in the current directory
+run_command "." "dart analyze ." "dart analyze"
 
-result=$(dart analyze .)
-exitCode=$? # If the exitCode is zero, then command executed successfully.
-
-if [ $exitCode  -ne 0 ]; then
-  echo "$result"
-fi
 echo "Finished running dart analyze command."
 
-################################################################
+# Run dart fix --apply and add updated files to git
+run_command "." "dart fix --apply && git add ." "dart fix"
 
-#  Run `dart dry --apply` to auto-fix basic issues.
-result=$(dart fix --apply)
-exitCode=$?
-
-# Adding the files updated by `dart fix` command to git.
-git add .
-
-echo "$result"
-
-if [ $exitCode -ne 0 ]; then
-  echo "dart fix command failed to execute."
-  exit 1
-fi
 echo "Finished running dart fix command."
